### ISSUE TITLE
Password won't display on arrismon's WebUI.

### ISSUE THREAD

**Issue by WRKDBF-Guy** [WRKDBF-Guy/arrismon#1]
I've tried everything I can think of to make the password (ie: encrypted at this point) display in the WebUI (via mods to arrismon.js).  The encryption string is stored in the file .secret_vault.txt (which has a symbolic in to .secret_vault.htm).  But with my limited knowledge, I'm having no luck.

**Comment by dave14305** [comment]
Updating the js file doesn't change anything because the actual JavaScript code that is executed is in that long blob in the asp file. You would be better served to re-combine the css and js code into the asp file so you can see everything web-related in one file.

Since your password is encrypted, you would need to make sure you have a way to decrypt it in the ASP file, if you really must insist on displaying the password. I wouldn't fight too hard to display an encrypted password. Accept a new password and allow it to be changed, but don't bother to display the actual password.

If you want to start simpler, you can add the password as a setting in the custom_settings.txt, but base64 encode it to ensure any special chars don't break the HTML when read. There are examples of base64-encoding and decoding in one of my earlier projects: https://github.com/dave14305/Unbound-Merlin-UI. I wasn't storing passwords, but used base64 to handle multi-line input text that could also have spaces.

Once you get that working in the UI, you can try to go back to trying to make it super encrypted.

**Comment by WRKDBF-Guy** [comment]
I actually find some of this oddly satisfying.  I searched and searched
trying to figure out how/where the JS file was getting installed and/or
executed.  It turns out it isn't.  I guess it's just stored as a separate
file in Github for clarity purposes, not actually for code to be modified.
Weird and confusing as heck.  Where does that blob line in the ASP file
come from BTW?  Surely someone didn't enter all that.  Or maybe that is
just one monstrously long line that equals the code in the JS file.  Do
most of you web builders use some sort of graphical web code generator or
something?

I'm thinking of moving the encrypted password back into the Config file -
where I had it for a while.  That should cause it to be displayed at least
- along with all the other Config data that is in there.

Bill

PS: no reply required.  Just glad to know that I didn't miss something
obvious.  I *have* learned one heck of lot about linux, scripting and (some
parts) of web building.  That web UI stuff is just weird and certainly not
intuitive.

**Comment by dave14305** [comment]
I would suggest you merge my Pull request #2 before continuing with any more development.

**Comment by WRKDBF-Guy** [comment]
Done.  Thanks.

**Comment by WRKDBF-Guy** [comment]
I'm closing this issue.

I've decided to take Dave's advice and not try to display the (current, stored) password on the WebUI.  I will just capture the entered password and pass it back to the shell script - and then encrypt it and store it there.  I will be attempting to authenticate the entered login name and password in the WebUI eventually, but not right yet; 1st things 1st; capturing, encrypting and storing the password properly.
